---

- name: Ensures /var/log/storm dir exists
  file: path={{item}} state=directory
  with_items:
     - "/var/log/storm"
     - "{{storm_dir}}/logback"
     - "{{storm_dir}}/logs"

- name: creating storm.yml
  template: src=storm.yaml-{{storm_ver}}.j2 dest={{storm_dir}}/conf/storm.yaml

- name: creating default env variables
  template: src=storm_env.ini.j2 dest={{storm_dir}}/conf/storm_env.ini

- name: copying cluster.xml
  template: src=cluster.xml-{{storm_ver}}.j2 dest={{storm_dir}}/conf/cluster.xml

- name: copying worker.xml
  template: src=worker.xml.j2 dest={{storm_dir}}/conf/worker.xml

- name: delete previous supervisor conf (supervisor/logviewer)
  command: "rm -rf /etc/supervisor/conf.d/storm-{{item}}.conf"
  with_items:
    - supervisor
    - logviewer

- name: stopping supervisor
  service: >-
    name=supervisor
    state=stopped
    enabled=yes

- name: delete previos supervisor conf (supervisor/logviewer)
  command: "rm -rf /etc/supervisor/conf.d/storm-{{item}}.conf"
  with_items:
    - nimbus
    - drpc
    - ui
  sudo: yes

- name: configure supervisor (nimbus/drpc/ui)
  template: src="supervisord.j2" dest=/etc/supervisor/conf.d/storm-{{item}}.conf  owner=root group=root mode=0751
  with_items:
    - nimbus
    - drpc
    - ui
  notify:
    - restart zookeeper
    - restart supervisor
  when: "storm_master is defined"

#- name: Configure storm-ui to be a daemon
#  template: >-
#    src=deamon.j2
#    dest=/etc/init.d/storm-ui-daemon
#    owner=root
#    group=root
#    mode=0751
#  notify:
#    - restart storm-ui
#  when: "storm_master is defined"

- name: delete previos supervisor conf (supervisor/logviewer)
  command: "rm -rf /etc/supervisor/conf.d/storm-{{item}}.conf"
  with_items:
    - supervisor
    - logviewer
  sudo: yes

- name: configure supervisor (supervisor/logviewer)
  template: src="supervisord.j2" dest="/etc/supervisor/conf.d/storm-{{item}}.conf"  owner=root group=root mode=0751
  with_items:
    - supervisor
    - logviewer

- name: delete storm-local & restart supervisor
  command: rm -rf '{{storm_dir}}/storm-local'
  sudo: yes
  notify:
    - restart supervisor

#sudo mkdir -p /mnt/seizure_data
#sudo mount -t cifs //192.168.13.101/smirnp /mnt/seizure_data -o user=nano,password=Yt1NyDpQNm

#- name: mount 13.101 share
#  command: "mkdir -p /mnt/seizure_data"
#  with_items:
#    - supervisor
#    - logviewer
#  notify:
#    - restart supervisor



