---
- name: "provision blades to be VM carriers"
  hosts: vm_hosts
  sudo: yes
  roles:
    - {role: ../../ansible-bdas/roles/common}
    - {role: kbrebanov.virtualbox}
    - {role: andrewrothstein.vagrant}
    - {role: dochang.docker, docker_users: [nano]}
    - {role: andrewrothstein.docker-compose}
  tags:
    - blades_provision

- name: "copy vagrant files to create VMs environment"
  hosts: vm_hosts
  sudo: yes
  tasks:
    - include_vars: "vars/main.yml"
    - name: "fetch repository"
      git: repo=https://github.com/itmo-escience/ansible-scripts.git
           dest=/opt/ansible-scripts
           version=refactoring
           accept_hostkey=yes
    - name: "prepare config for vagrant"
      copy: content="{{ blades[inventory_hostname] }}" dest=/opt/ansible-scripts/settings.yml
  tags:
    - vagrant_configuration

