---
#storm_ver : '0.10.0'
#storm_mirror : 'http://mirror.cc.columbia.edu/pub/software/apache/storm'
storm_ver : '0.11.0'
#storm_mirror : 'http://mirror.cc.columbia.edu/pub/software/apache/storm'
#http://mirror.cc.columbia.edu/pub/software/apache/storm/apache-storm-0.11.0/apache-storm-0.11.0.tar.gz
#http://192.168.1.36/apache-storm-0.11.0/apache-storm-0.11.0.tar.gz
storm_mirror : 'http://192.168.1.36'
storm_dir : '/opt/storm'

storm_name : 'apache-storm-{{ storm_ver }}'
storm_archive : '{{ storm_name }}.tar.gz'
storm_url : '{{storm_mirror}}/{{storm_name}}/{{ storm_archive}}'


proxy_env:
          http_proxy: http://proxy.ifmo.ru:3128
          HTTP_PROXY: http://proxy.ifmo.ru:3128
          no_proxy: 192.168.1.36
zkid: "zookeeper"

#service deamon
user: vagrant
#There two fields are specified during daemon-template copying
#service_name: ganglia-api-daemon
#daemon: "python {{ganglia_api_dir}}/ganglia/ganglia_api.py &"
pidfile: /var/run/{{service_name}}.pid
daemon_opts: ""