---
- name: install openmpi packages
  apt: name={{ item }} state=installed
  with_items:
    - openmpi-bin
    - openmpi-doc
    - libopenmpi-dev

- name: populate mpi_hosts
  template: src=etc/mpi_hosts.j2 dest=/etc/openmpi/openmpi-default-hostfile
