
# Path to the ganglia configuration.
ganglia_config_dir: /etc/ganglia

# Path to init scripts.
ganglia_init_d_dir: /etc/init.d

# Location of the gmond binary.
ganglia_gmond_binary: /usr/sbin/gmond

ganglia_api_dir: /opt/ganglia-api

#ganglia-api service deamon
user: vagrant
service_name: ganglia-api-daemon
daemon: "python {{ganglia_api_dir}}/ganglia/ganglia_api.py &"
pidfile: /var/run/{{service_name}}.pid
daemon_opts: ""

# Location of the httpd configurations. Used to install the web frontend configuration.
httpd_conf_d_dir: /etc/apache2/conf-enabled

# Location of the web frontend on the system.
ganglia_web_path: /usr/share/ganglia-webfrontend

# Directory where modules are located.
ganglia_lib_dir: /usr/lib/ganglia