---
#tasks file for anaconda
- name: download installer.sh
  get_url: >
    url={{anaconda_installer_url}}
    dest=/tmp/{{anaconda_installer_sh}}
    owner=root
    group=root
    mode=0755

- name: installing conda
  command: /tmp/{{anaconda_installer_sh}} -b -p /opt/{{anaconda_name}}
  args:
    creates: /opt/{{anaconda_name}}/bin/conda

- name: deleting installer...
  when: anaconda_cleanup
  file:
    path=/tmp/{{anaconda_installer_sh}}
    state=absent

- name: link anaconda...
  file:
    dest=/opt/anaconda
    src=/opt/{{anaconda_name}}
    state=link
    owner=root
    group=root

- name: install additional packages...
  command: /opt/anaconda/bin/conda install -y {{item}}
  with_items: '{{ anaconda_pkg_list }}'

- name: conda updates
  command: /opt/anaconda/bin/conda update -y --all

- name: remove conda-curl since it conflicts with the system curl
  command: /opt/anaconda/bin/conda remove -y curl

- name: make system default python etc...
  when: anaconda_make_sys_default
  copy: >-
    src=etc/profile.d/anaconda.sh
    dest=/etc/profile.d/anaconda.sh
    mode=0644
    owner=root
    group=root
  sudo: True

- name: chmod /etc/environment 777
  file: path=/etc/environment mode=0777

- name: adding anaconda path to environment
  shell: 'echo "PATH=/opt/anaconda/bin:/opt/anaconda/lib:$PATH" >> /etc/environment'
  sudo: yes

- name: chmod /etc/environment 644
  file: path=/etc/environment mode=0644