---
- name: deploy standalone Spark
  hosts: all
  roles:
    - { role: spark_standalone }
  any_errors_fatal: yes
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128



- name: deploy Spark on Mesos
  hosts: spark_masters
  roles:
    - { role: spark_mesos }
  any_errors_fatal: yes
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128
