---
- name: Ensures /var/log/storm dir exists
  file: path={{item}} state=directory
  with_items:
     - "/var/log/storm"
     - "{{storm_dir}}/logback"
     - "{{storm_dir}}/logs"
  tags:
    - configure

- name: stopping supervisor
  service: >-
   name=supervisor
   state=stopped
   enabled=yes
  ignore_errors: yes
  tags:
    - restart


- name: creating default env variables
  template: src=storm_env.ini.j2 dest={{storm_dir}}/conf/storm_env.ini
  tags:
    - configure

- name: copying cluster.xml
  when: "master is defined"
  template: src=Cluster.xml-{{storm_ver}}.j2 dest={{storm_dir}}/conf/cluster.xml
  tags:
    - configure

- name: creating storm.yml
  template: src=storm.yaml-{{storm_ver}}.j2 dest={{storm_dir}}/conf/storm.yaml
  when: "slave is defined"
  tags:
    - configure

- name: copying worker.xml
  when: "slave is defined"
  template: src=worker.xml.j2 dest={{storm_dir}}/conf/worker.xml
  tags:
    - configure


#- name: stopping supervisor
#  service: >-
#    name=supervisor
#    state=stopped
#    enabled=yes
#  ignore_errors: yes
#  tags:
#    - configure
#    - restart

- name: delete previos supervisor-master conf (nimbus, drpc, ui)
  when: "master is defined"
  command: "rm -rf /etc/supervisor/conf.d/storm-{{item}}.conf"
  with_items:
    - nimbus
    - drpc
    - ui
  tags:
    - configure

- name: creating supervisor-slave conf.d (nimbus, drpc, ui)
  when: "master is defined"
  template: src="supervisord.j2" dest=/etc/supervisor/conf.d/storm-{{item}}.conf  owner=root group=root mode=0751
  with_items:
    - nimbus
    - drpc
    - ui
  tags:
    - configure
    - master

#- name: Configure storm-ui to be a daemon
#  template: >-
#    src=deamon.j2
#    dest=/etc/init.d/storm-ui-daemon
#    owner=root
#    group=root
#    mode=0751
#  notify:
#    - restart storm-ui
#  when: "storm_master is defined"

- name: deleting previous supervisor-slave conf (supervisor,logviewer)
  when: "slave is defined"
  command: "rm -rf /etc/supervisor/conf.d/storm-{{item}}.conf"
  with_items:
    - supervisor
    - logviewer
  sudo: yes
  tags:
    - configure

- name: creating supervisor-slave conf.d (supervisor,logviewer)
  when: "slave is defined"
  template: src="supervisord.j2" dest="/etc/supervisor/conf.d/storm-{{item}}.conf"  owner=root group=root mode=0751
  with_items:
    - supervisor
    - logviewer
  tags:
    - configure

- name: deleting storm-local
  command: rm -rf '{{storm_dir}}/storm-local'
  sudo: yes
  tags:
    - configure
    - restart

- name: restarting supervisor
  command: service supervisor restart
#  service: >-
#   name=supervisor
#   enabled=yes
  tags:
    - configure
    - restart






