---

- include_vars: "main.yml"

- include: install.yml
  when: "master is defined or slave is defined"

- include: configure.yml
  when: "master is defined or slave is defined"

- include: install_wave.yml
  when: "wave is defined"