---
- name: Download Spark pre-built package
  get_url: url={{ spark_download_url }} dest="/tmp/{{ spark_distribution }}.tgz"
  tags:
    - install

- name: Extract Spark archive
  unarchive: copy=no src="/tmp/{{ spark_distribution }}.tgz" dest=/usr/lib
  sudo: yes
  tags:
    - install

- name: Create link to Spark directory
  file: src=/opt/{{ spark_distribution }} dest={{ spark_root }} state=link
  sudo: yes
  tags:
    - install

#- include_vars: roles/hadoop_common/vars/main.yml
#  tags:
#    - configure

#- include_vars: roles/tachyon/vars/main.yml
#  tags:
#    - configure

#- name: Configure Spark to run in standalone deploy mode
#  template: src=conf/spark-env.sh.j2 dest={{ spark_root }}/conf/spark-env.sh
#  sudo: yes
#  tags:
#    - configure
#
#- name: populate conf/slaves file
#  template: src=conf/slaves.j2 dest={{ spark_root }}/conf/slaves
#  sudo: yes
#  tags:
#    - configure
#
#- name: increase default spark.executor.memory parameter
#  template: src=conf/spark-defaults.conf.j2 dest={{ spark_root }}/conf/spark-defaults.conf
#  sudo: yes
#  tags:
#    - configure

