dest_dir: /opt/monitoring_services

daemon_name: "java -jar "
daemon_user: vagrant

dstorage_log_dir: /var/log/dstorage-core
mongoHost: 192.168.13.132

services:
   'computations-monitor':
      namespace: itmo.escience.dapris.monitoring.computations.ComputationsMonitor
   'infrastructure-monitor':
      namespace: itmo.escience.dapris.monitoring.infrastructure.InfrastructureMonitor


iperf_daemon:
    'key1':
      service_name: iperf-server
      user: vagrant
      daemon: "/usr/bin/iperf"
      daemon_opts: "-s"

