---
# Run with   $ ansible-playbook site.yml --skip-tags: 'stop' See: site.yml

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
  any_errors_fatal: yes

- name: install java and scala
  hosts: all
  sudo: yes
  roles:
    - java
    - andrewrothstein.scala
  any_errors_fatal: yes

- name: create non-root clusteruser user
  hosts: all
  sudo:	yes
  roles:
    - clusteruser_common
  any_errors_fatal: yes