---
- sshkey_path: "/home/nano/.ssh/id_rsa_nano_blades"
- username: "nano"

- servers:
    - server: "192.168.13.109"
      ip: "192.168.13.109"
      storage_pool_name: "fcpir_500G"
      vms:
        - name: "node-92-71"
          ip: "192.168.92.71"
          cpus: 32
          memory: 70000

    - server: "192.168.13.110"
        ip: "192.168.13.110"
        storage_pool_name: "fcpir_500G"
        vms:
          - name: "testvm"
            ip: "192.168.92.72"
            cpus: 32
            memory: 70000

    - server: "192.168.13.111"
        ip: "192.168.13.111"
        storage_pool_name: "fcpir_500G"
        vms:
          - name: "node-92-73"
            ip: "192.168.92.73"
            cpus: 32
            memory: 70000

    - server: "192.168.13.112"
        ip: "192.168.13.112"
        storage_pool_name: "fcpir_500G"
        vms:
          - name: "node-92-73"
            ip: "192.168.92.73"
            cpus: 32
            memory: 70000