---

- name: Configuring deaemons
  template: >-
    src=deamon.j2
    dest=/etc/init.d/{{item.key}}
    owner=root
    group=root
    mode=0751
  with_dict: services
  tags:
    - configure

- name: restarting daemons
  service: >-
    name={{item.key}}
    state=restarted
    enabled=yes
  sudo: yes
  with_dict: services
  tags:
    - configure

# Configures and starts the td-agent service for

- name: creating td-agent.conf
  template: src=fluentd.conf.j2 dest=/etc/td-agent/td-agent.conf
  tags:
    - configure
    - td-agent

#- name: creating pos-files2
#  command: >-
#    touch {{item}}
#  with_items:
#    - {{dstorage_log_dir}}/logs.pos
#    #- /var/log/dstorage/requests.pos
#  sudo: yes-tags

#- name: Ensures {{dstorage_log_dir}}/pos dir exists
#  file: path={{dstorage_log_dir}}/pos state=directory
#  tags:
#    - configure
#    - td-agent

- name: creating pos-file
  command: "touch {{dstorage_log_dir}}/logs.pos"
  tags:
    - configure
    - td-agent

- name: configuring chmod
  #command: chmod -R 777 /var/log/dstorage
  command: chmod -R 777 {{dstorage_log_dir}}
  sudo: yes
  notify:
    - restart td-agent
  tags:
    - configure
    - td-agent



#- name: creating pos-files
#  file: path={{item}} state=directory
#  with_items:
#    - /var/log/dstorage/
#    - /var/log/dstorage/logs/
#  sudo: yes
#  tags:
#    - install
#    - td-agent