- name: create {{dest_dir}} dir
  file: path={{dest_dir}} state=directory
  when: "monitoring is defined"
  tags:
    - install
    - monitoring

- name: copy sshKeys
  copy: src=../sshkey/id_rsa dest={{dest_dir}}/id_rsa
  when: "monitoring is defined"
  tags:
    - install
    - monitoring


- name: clean dest dirs
  file: path={{dest_dir}}/{{item.key}} state=absent
  with_dict: services
  when: "monitoring is defined"
  tags:
    - install
    - monitoring

- name: copy repo deploy key to obtain sources
  synchronize: src={{item.key}} dest={{dest_dir}}
  with_dict: services
  when: "monitoring is defined"
  tags:
    - install
    - monitoring

- name: copy common Mongo.conf files
  template: src=Mongo.conf dest={{dest_dir}}/{{item.key}} owner=root group=root mode=0751
  with_dict: services
  when: "monitoring is defined"
  tags:
    - install
    - monitoring


### Installing fluentd required files
- name: install fluent-plugin-multi-format-parser
  when: "td-agent is defined"
  command: /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-multi-format-parser
  sudo: yes
  tags:
    - install
    - td-agent

- name: create /etc/td-agent dir
  when: "td-agent is defined"
  #command: fluentd --setup /etc/td-agent
  command: mkdir -p /etc/td-agent
  sudo: yes
  tags:
    - install
    - td-agent


## I-perf
- name: install iperf
  when: "iperf is defined"
  apt: >-
    name=iperf
    state=latest
  when: "is_iperf is defined"
  tags:
    - iperf
    - install

- name: add iperf user
  when: "iperf is defined"
  user: name=iperf shell=/sbin/nologin
  when: "is_iperf is defined"
  tags:
    - iperf
    - install
