# -*- mode: ruby -*-
# vi: set ft=ruby :

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://proxy.ifmo.ru:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1,"
  end


  # Specify minimum Vagrant version and Vagrant API version
  Vagrant.require_version ">= 1.6.0"
  VAGRANTFILE_API_VERSION = "2"

  # Require YAML module
  require 'yaml'

  # Read YAML file with box details
  servers = YAML.load_file('cluster-description.yml')

  # Create boxes
  Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Iterate through entries in YAML file
    servers.each do |server|
      config.vm.define server["name"] do |srv|
        srv.vm.box = "ubuntu/trusty64"
        srv.vm.hostname = server["name"]

        srv.vm.provider :virtualbox do |vb|
          vb.memory = server["ram"]
          vb.cpus = server["cpus"]
        end

        srv.vm.network "public_network", ip: server["ip"], netmask: "255.255.0.0", bridge: "enp22s0f5"

        srv.vm.synced_folder "hdfs_data/data_#{server["name"]}", "/hdfs_data", create: true, mount_options: ["dmode=777,fmode=777"]
        srv.vm.synced_folder ".", "/home/vagrant/project", :mount_options => ["dmode=700","fmode=600"]


        srv.vm.provision "shell", path: "install-sshkey.sh"

        srv.vm.provision "shell" do |s|
            dns_server = "if ! grep -q \'nameserver 192.168.13.132\' /etc/resolvconf/resolv.conf.d/head; then echo 'nameserver 192.168.13.132'|tee --append /etc/resolvconf/resolv.conf.d/head; fi;resolvconf -u;"
            default_iface = ""
            hosts_file = "echo '127.0.0.1 localhost'|tee /etc/hosts;echo '#{server["ip"]} #{server["name"]}'|tee --append /etc/hosts;"
            s.inline = "#{hosts_file}#{dns_server}#{default_iface}"
            s.privileged = true
        end

      end
    end
  end


