---

#Configures the gmetad service.

- name: Ensure the gmetad user exists
  user: >-
    name="{{ ganglia_config_gmetad.setuid_username }}"
    system=yes
    state=present
  when: ganglia_meta is defined
  tags:
    - ganglia-meta
    - configure

- name: Ensure the gmetad directory exists
  file: >-
    path="{{ ganglia_config_gmetad.rrd_rootdir }}"
    owner="{{ ganglia_config_gmetad.setuid_username }}"
    group=root
    mode=0755
    state=directory
  when: "ganglia_meta is defined"
  tags:
    - ganglia-meta
    - configure

- name: Configure the gmetad
  template: >-
    src=gmetad.conf.j2
    dest={{ ganglia_config_dir }}/gmetad.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart ganglia-meta
  when: "ganglia_meta is defined"
  tags:
    - ganglia-meta
    - configure

# Configure the gmond service

- name: Disable the default Ganglia Monitor
  service: >-
    name=gmond
    enabled=no
    state=stopped
  when: "ansible_os_family == 'RedHat' and ganglia_monitor is defined"
  tags:
    - ganglia-monitor
    - configure

- name: Disable the default Ganglia Monitor
  service: >-
    name=ganglia-monitor
    enabled=no
    state=stopped
  when: ansible_os_family == 'Debian' and ganglia_monitor is defined
  tags:
    - ganglia-monitor
    - configure

- name: Copy diskstat.pyconf to {{ ganglia_config_dir }}/conf.d
  template: >-
    src=diskstat.pyconf.j2
    dest={{ ganglia_config_dir }}/conf.d/diskstat.pyconf
    owner=root
    group=root
    mode=0644
  with_dict: "{{ganglia_config_gmond}}"
  when: "ganglia_monitor is defined"
  tags:
    - ganglia-monitor
    - configure

- name: Configure Ganglia Monitors
  template: >-
    src=gmond.conf.j2
    dest={{ ganglia_config_dir }}/gmond-{{ item.key }}.conf
    owner=root
    group=root
    mode=0644
  with_dict: "{{ganglia_config_gmond}}"
  when: "ganglia_monitor is defined"
  tags:
    - ganglia-monitor
    - configure

- name: Configuring init scripts for Ganglia Monitors
  template: >-
    src=gmond-{{ ansible_os_family }}.service.j2
    dest={{ ganglia_init_d_dir }}/gmond-{{ item.key }}
    owner=root
    group=root
    mode=0755
  with_dict: "{{ganglia_config_gmond}}"
  when: ganglia_monitor is defined
  tags:
    - ganglia-monitor
    - configure

- name: Ensure Ganglia Monitor services are enabled and started
  service: >-
    name=gmond-{{ item.key }}
    enabled=yes
    state=restarted
  with_dict: "{{ganglia_config_gmond}}"
  when: ganglia_monitor is defined
  tags:
    - ganglia-monitor
    - configure
    - ganglia_restart

# Configures the web frontend service in apache

- name: Copy diskstat_report.json.j2 to {{ ganglia_webfrontend_dir }}/graph.d
  template: >-
    src=diskstat_report.json.j2
    dest={{ ganglia_webfrontend_dir }}/graph.d/diskstat_report.json
    owner=root
    group=root
    mode=0644
  notify:
    - restart ganglia-meta
  when: "ganglia_web is defined"
  tags:
    - ganglia-web
    - configure

- name: Enable the apache2 frontend
  template: >-
    src=webfrontend-apache.conf.j2
    dest={{ httpd_conf_d_dir }}/ganglia.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart apache2
  when: ganglia_web is defined
  tags:
    - ganglia-web
    - configure


##Configures ganglia-api settings.py

- name: Configure ganglia-api before run
  template: >-
    src=ganglia-api-settings.py.j2
    dest={{ ganglia_api_dir }}/ganglia/settings.py
    owner=root
    group=root
    mode=0644
  when: ganglia_api is defined
  tags:
    - ganglia-api
    - configure


#- name: "Debugging"
#  debug: msg={{ganglia-api-daemon}}

- name: Configure ganglia-api to be a daemon
  template: >-
    src=deamon.j2
    dest=/etc/init.d/ganglia-api-daemon
    owner=root
    group=root
    mode=0751
  with_dict: "{{ganglia_api_daemon}}"
  notify:
    - restart ganglia-api
  when: ganglia_api is defined
  tags:
    - ganglia-api
    - configure


