---
#
# Ganglia Monitor is installed on all nodes.
# The Python modules support is automatically added.
- name: Install Ganglia Monitor (RedHat)
  yum: >-
    name={{item}}
    state=latest
  with_items:
    - ganglia-gmond
    - ganglia-gmond-python
  when: "ansible_os_family == 'RedHat'"
  tags:
    - ganglia-monitor
    - install

- name: Install Ganglia Monitor (Debian)
  apt: >-
    name={{item}}
    state=present
  with_items:
    - ganglia-monitor
    - ganglia-monitor-python
  when: "ansible_os_family == 'Debian'"
  tags:
    - ganglia-monitor
    - install

# Ganglia Meta is installed only on nodes marked is_ganglia_meta=1
- name: Install Ganglia Meta
  yum: >-
    name={{item}}
    state=present
  with_items:
    - ganglia-gmetad
  when: ansible_os_family == 'RedHat' and ganglia_meta is defined
  tags:
    - ganglia-meta
    - install

- name: Install Ganglia Meta
  apt: >-
    name={{item}}
    state=latest
  with_items:
    - gmetad
  when: "ansible_os_family == 'Debian' and is_ganglia_meta is defined"
  tags:
    - ganglia-meta
    - install

# Ganglia Web is installed only on nodes marked is_ganglia_web=1
- name: Install Ganglia Web/Apache2
  yum: >-
    name={{item}}
    state=latest
  with_items:
    - ganglia-web, git, apache2
  when: "ansible_os_family == 'RedHat' and is_ganglia_web is defined"
  tags:
    - ganglia-web
    - install

- name: Install Ganglia Web/Apache2
  apt: >-
    name={{item}}
    state=latest
  with_items:
    - ganglia-webfrontend, apache2
  when: "ansible_os_family == 'Debian' and is_ganglia_web is defined"
  tags:
    - ganglia-web
    - install

# Ganglia API
- name: Install Ganglia API
  git: repo=https://github.com/smirnp/ganglia-api.git
       dest={{ ganglia_api_dir }}
       clone=yes
  when: "is_ganglia_api is defined"
  tags:
    - ganglia-web
    - install

- name: Install Tornado
  pip: >-
    name={{item}}
  with_items:
    - tornado
  when: "is_ganglia_api is defined"
  tags:
    - ganglia-api
    - install

