---
- name: install necessary tools
  apt: name={{ item }} state=present update_cache=no
  with_items:
    - git
    - gradle
  tags:
    - install

- name: correct /usr/lib/jvm/default-java value
  file: src=/usr/lib/jvm/java-8-oracle dest=/usr/lib/jvm/default-java state=link

- name: copy repo deploy key to obtain sources
  copy: src=../repo-keys/dstorage-core/id_rsa dest={{core_repo_key_path}} mode=0700
  tags:
    - install

- name: clean clone dir - {{core_clone_dir}}
  file: path={{core_clone_dir}} state=absent

- name: obtain dstorage-core sources
  git: repo=git@github.com:itmo-escience/dstorage-core.git
    version={{core_tag}}
    dest={{core_clone_dir}}
    accept_hostkey=True
    key_file="{{core_repo_key_path}}"
    clone=yes update=yes
  tags:
      - install

- name: build dstorage-core
  shell: "gradle makeJar -Dhttp.proxyHost=proxy.ifmo.ru -Dhttp.proxyPort=3128"
  args:
    chdir: "{{core_clone_dir}}"
  tags:
      - install

- name: Ensures {{core_install_dir}} installation dir exists
  file: path={{core_install_dir}} state=directory
  tags:
      - install

- name: install dstorage-core executable from {{core_clone_dir}}/build/libs to dir {{core_install_dir}}
  shell: "cp {{core_clone_dir}}/build/libs/dstorage-core-{{core_version}}.jar {{core_install_dir}}/dstorage-core.jar"
  tags:
      - install

- name: ensure {{core_install_dir}}/dstorage-core.jar exists
  file: dest={{core_install_dir}}/dstorage-core.jar state=file
  tags:
      - install

- name: Create service conf file /etc/init/dstorage-core.conf
  template: src=dstorage-core.conf.j2 dest=/etc/init/dstorage-core.conf
  tags:
     - install

- name: Disable service dstorage-core
  service: name=dstorage-core state=stopped enabled=no
  tags:
      - install

- name: configure dstorage-core Core.cfg
  template: src=Core.cfg.j2 dest={{core_install_dir}}/Core.cfg
  notify:
      - Restart dstorage-core
  tags:
      - configure

- name: Ensure Core.ct present
  copy: src=Core.ct dest={{core_install_dir}}/Core.ct
  notify:
      - Restart dstorage-core
  tags:
      - configure

- name: Ensure clientaccesspolicy.xml present
  copy: src=clientaccesspolicy.xml dest={{core_install_dir}}/clientaccesspolicy.xml
  notify:
      - Restart dstorage-core
  tags:
      - configure

- name: start and enable service dstorage-core
  service: name=dstorage-core state=started enabled=yes
  tags:
    - start

#- name: stop and disable service dstorage-core
#  service: name=dstorage-core state=stopped enabled=no
#  tags:
#    - stop

