# This script currently runs mesos on hosts which is listed in the file 'hosts'
# It can be run as a single node as a multi node cluster
# ATTENTION! There is a set of tags: install, configure, start, stop
# These tags manage lifecycle of the overall system, see examples
# Examples:
# 1) Installs, configure and runs the whole cluster
#   $ ansible-playbook site.yml --skip-tags: 'stop'
# 2) Stops the cluster
#  $ ansible-playbook site.yml --tags: 'stop'
# 3) Resume execution
#  $ ansible-playbook site.yml --tags: 'start'
# 4) Reconfigurates the cluster (Affected slave and master services will be restarted automatically)
#  $ ansible-playbook site.yml --tags: 'configure'
# 5) Just slaves or masters can be under commmand
#   ansible-playbook site.yml --tags: "stop,mesos-masters"
# ansible-playb
---
- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
  any_errors_fatal: yes
  environment:
            http_proxy: http://proxy.ifmo.ru:3128
            HTTP_PROXY: http://proxy.ifmo.ru:3128

- name: create non-root clusteruser user
  hosts: all
  sudo:	yes
  roles:
    - clusteruser_common
  any_errors_fatal: yes
  environment:
            http_proxy: http://proxy.ifmo.ru:3128
            HTTP_PROXY: http://proxy.ifmo.ru:3128

- name: install, configure and run the mesos masters
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "master", mesos_cluster_mode: "masters_file", tags: ['mesos-masters']}
  environment:
            http_proxy: http://proxy.ifmo.ru:3128
            HTTP_PROXY: http://proxy.ifmo.ru:3128

- name: install, configure and run the mesos slaves
  hosts: mesos_slaves
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "slave", mesos_cluster_mode: "masters_file", tags: ['mesos-slaves']}
  environment:
            http_proxy: http://proxy.ifmo.ru:3128
            HTTP_PROXY: http://proxy.ifmo.ru:3128

  - name: install ganglia monitors
    hosts: ganglia_monitors
    sudo: True
    roles:
      - { role: ganglia , tags: ['ganglia-monitors']}
    environment:
                http_proxy: http://proxy.ifmo.ru:3128
                HTTP_PROXY: http://proxy.ifmo.ru:3128

  - name: install ganglia meta
    hosts: ganglia_meta
    sudo: True
    roles:
      - { role: ganglia, is_ganglia_meta: 1,  tags: ['ganglia-meta']}
    environment:
                http_proxy: http://proxy.ifmo.ru:3128
                HTTP_PROXY: http://proxy.ifmo.ru:3128

  - name: install ganglia web
    hosts: ganglia_web
    sudo: True
    roles:
      - { role: ganglia, is_ganglia_web: 1,  tags: ['ganglia-web']}
    environment:
                http_proxy: http://proxy.ifmo.ru:3128
                HTTP_PROXY: http://proxy.ifmo.ru:3128

#- include: tests/integration-tests.yml
