---
- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
  any_errors_fatal: yes

# TODO: all machines should have the same user
- name: create non-root clusteruser user
  hosts: all
  sudo:	yes
  roles:
    - clusteruser_common
  any_errors_fatal: yes

- name: install Mesos slaves
  hosts: worker
  sudo:	yes
  vars_files:
    - group_vars/components.yml
  roles:
    - { role: mesos_slave}
  any_errors_fatal: yes

- name: install Mesos masters
  hosts: master
  sudo:	yes
  vars_files:
    - group_vars/components.yml
  roles:
    - { role: mesos_master}
  any_errors_fatal: yes
#
#- name: setup HDFS namenode
#  hosts: master
#  sudo:	yes
#  vars_files:
#    - group_vars/components.yml
#  roles:
#    - { role: hdfs_namenode, when: install_spark or install_mapred or install_mesos or install_tachyon }
#  any_errors_fatal: yes
#
#- name: setup HDFS datanodes
#  hosts: workers
#  sudo:	yes
#  vars_files:
#    - group_vars/components.yml
#  roles:
#    - { role: hdfs_datanode, when: install_spark or install_mapred or install_mesos or install_tachyon }
#  any_errors_fatal: yes

#- include: tests/integration-tests.yml
