---
- name: applying common roles
  hosts: all
  sudo: True
  roles:
    - { role: ntp, tags: ntp }
    - { role: williamyeh.oracle-java, java_download_from_oracle: true, tags: java }
    - { role: tecris.maven, tags: ['maven', 'dstorage-core','dstorage-agents'] }
    - { role: davidkarban.git, tags: ['git', 'dstorage-core','dstorage-agents'] }
  vars_files: 
    - vars/proxy.yml
  environment: "{{proxy_env}}"
  tags:
    - common

- name: applying storm_master hosts
  hosts: storm_master
  sudo: True
  roles:
    - { role: storm_on_mesos, master: 1, tags: master }
    - { role: ganglia, ganglia_meta: true, ganglia_web: true, ds1_source: 192.168.92.14, tags: ganglia }
  environment: "{{proxy_env}}"
  tags:
    - master

- name: applying storm_slave hosts
  hosts: storm_slave
  sudo: True
  roles:
    - { role: storm_on_mesos, slave: 1, tags: slave }
    - { role: dstorage, dstorage_install_mode: "agent", oracle_java_set_as_default: yes, agent_hdd_dir: "/opt/hdd", agent_ssd_dir: "/opt/ssd", core_address: "node-92-11", core_address0: "{{groups['dstorage-core'][0]}}", tags: dstorage-agents }
    - { role: wfdb, tags: wfdb }
    - { role: ganglia, is_ganglia_monitor: false }
    - { role: anaconda, storm_slave: 1, anaconda_make_sys_default: true, tags: anaconda }
  environment: "{{proxy_env}}"
  tags:
    - slave


