---
- name: process storm_master hosts
  hosts: storm_master
  sudo: True
  roles:
    - { role: storm_on_mesos, storm_master: 1, tags: master }
    - { role: anaconda, storm_master: 1, anaconda_make_sys_default: true, tags: anaconda }
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128
  tags:
    - master

- name: process storm_slave hosts
  hosts: storm_slave
  sudo: True
  roles:
    - { role: storm_on_mesos, storm_slave: 1, tags: slave }
    - { role: anaconda, storm_slave: 1, anaconda_make_sys_default: true, tags: anaconda }
  environment:
              http_proxy: http://proxy.ifmo.ru:3128
              HTTP_PROXY: http://proxy.ifmo.ru:3128
  tags:
    - slave