---
# - name: applying storm_master hosts
  # hosts: storm_master
  # sudo: True
  # roles:
    # - { role: storm_on_mesos, master: 1, tags: master }
    # - { role: anaconda, storm_master: 1, anaconda_make_sys_default: true, tags: anaconda }
  # environment: "{{proxy_env}}"
  # tags:
    # - master

# - name: applying storm_slave hosts
  # hosts: storm_slave
  # sudo: True
  # roles:
    # - { role: storm_on_mesos, slave: 1, tags: slave }
    # - { role: anaconda, storm_slave: 1, anaconda_make_sys_default: true, tags: anaconda }
  # environment: "{{proxy_env}}"
  # tags:
    # - slave

# - name: applying ntp role
  # hosts: all
  # sudo: True
  # roles:
    # - { role: ntp, tags: ntp }
  # tags:
    # - ntp

- name: applying wave role
  hosts: storm_slave
  sudo: True
  roles:
     - { role: storm_on_mesos, wave : 1, tags: wave }
  tags:
    - wave 