---

- name: just debug
  hosts: all
  tasks:
    - debug: msg="{{groups['dstorage-mongodb'][0]}}"

- name: install mongodb for dstorage-core
  hosts: dstorage-mongodb
  sudo: True
  roles:
    - {role: mongodb}

- name: install, configure and run dstorage-core
  hosts: dstorage-core
  sudo: True
  roles:
    - { role: dstorage, dstorage_install_mode: "core", mongodb_address: "{{groups['dstorage-mongodb'][0]}}", java_version: "8", tags: ['dstorage-core']}

- name: install, configure and run dstorage-agent
  hosts: dstorage-agents
  sudo: True
  roles:
    - { role: dstorage, dstorage_install_mode: "agent", java_version: "8", tags: ['dstorage-core']}
