---
- name: install mongodb for dstorage-core
  hosts: dstorage-mongodb
  sudo: True
  roles:
    - {role: mongodb}

- name: install, configure and run dstorage-core
  hosts: dstorage-core
  sudo: True
  roles:
    - { role: dstorage, dstorage_install_mode: "core", mongodb_address: "{{groups['dstorage-mongodb'][0]}}", oracle_java_set_as_default: yes, tags: ['dstorage-core']}

- name: install, configure and run dstorage-agent
  hosts: dstorage-agents
  sudo: True
  roles:
    - { role: dstorage,
        dstorage_install_mode: "agent",
        oracle_java_set_as_default: yes,
        ## these two directories have to be created before this script !!!
        agent_hdd_dir: "/opt/hdd",
        agent_ssd_dir: "/opt/sdd",
        core_address: "{{groups['dstorage-core'][0]}}",
        tags: ['dstorage-core']}