# This test requires the role 'andrewrothstein.anaconda' to be installed
# you can do this with the command: 'ansible-galaxy install andrewrothstein.anaconda'
# see the reference: https://galaxy.ansible.com/detail#/role/6397

---
- name: test ganglia-api
  hosts: all
  sudo: yes
  roles:
    - { role: andrewrothstein.anaconda}
  tasks:
    - name: Install Git
      command: "/opt/anaconda/bin/python --version"
  environment:
    http_proxy: http://proxy.ifmo.ru:3128
    HTTP_PROXY: http://proxy.ifmo.ru:3128

