## core settings
core_port: 8084
core_version: 0.42.027
core_clone_dir: /tmp/dstorage-core
core_install_dir: /opt/dstorage-core
core_tag: v{{core_version}}
core_repo_key_path: /tmp/dstorage-core-id_rsa
mongodb_address: localhost
mongodb_port: 27017
security_level: 0
## agent settings
agent_tag: 6ab05e2dfb4935794cd0c542b23d10e3ccc3055f
agent_clone_dir: /tmp/dstorage-agent
agent_install_dir: /opt/dstorage-agent
agent_binary_name: dstorage-agent-0.0.1-jar-with-dependencies.jar
agent_repo_key_path: /tmp/dstorage-agent-id_rsa
agent_ssd_quota: 1000000
agent_mem_quota: 1000000
agent_quota: 50000

# this variables should be set in the playbook
## agent_hdd_dir:
## agent_ssd_dir:
## core_address